# Generated by Django 6.1 on 2026-10-03 09:13

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('national_id', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='National ID must contain exactly 13 digits.', regex='^\\d{13}$')])),
                ('nationality_code', models.CharField(choices=[('U', 'Unspecified'), ('SA', 'South Africa'), ('SDC', 'SADC except SA'), ('NAM', 'Namibia'), ('BOT', 'Botswana'), ('ZIM', 'Zimbabwe'), ('ANG', 'Angola'), ('MOZ', 'Mozambique'), ('LES', 'Lesotho'), ('SWA', 'Swaziland'), ('MAL', 'Malawi'), ('ZAM', 'Zambia'), ('MAU', 'Mauritius'), ('TAN', 'Tanzania'), ('SEY', 'Seychelles'), ('ZAI', 'Zaire'), ('ROA', 'Rest of Africa'), ('EUR', 'European countries'), ('AIS', 'Asian countries'), ('NOR', 'North American countries'), ('SOU', 'Central and South American countries'), ('AUS', 'Australia Oceania countries'), ('OOC', 'Other and rest of Oceania'), ('NOT', 'N/A: Institution')], max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('home_language_code', models.CharField(choices=[('Eng', 'English'), ('Afr', 'Afrikaans'), ('Oth', 'Other'), ('SASL', 'South African Sign Language'), ('Sep', 'sePedi'), ('Ses', 'seSotho'), ('Set', 'seTswana'), ('Swa', 'siSwati'), ('Tsh', 'tshiVenda'), ('Xho', 'isiXhosa'), ('Xit', 'xiTsonga'), ('Zul', 'isiZulu'), ('Nde', 'isiNdebele')], max_length=10)),
                ('citizen_resident_status', models.CharField(choices=[('SA', 'South Africa'), ('O', 'Other'), ('D', 'Dual (SA plus other)'), ('PR', 'Permanent Resident'), ('U', 'Unknown')], max_length=3)),
                ('home_address_1', models.CharField(max_length=255)),
                ('home_address_2', models.CharField(max_length=255)),
                ('home_address_3', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='ZA')),
                ('disability', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('disability_note', models.FileField(blank=True, null=True, upload_to='disability_notes/')),
                ('certified_id', models.FileField(upload_to='certified_ids/')),
                ('matric_certificate', models.FileField(blank=True, null=True, upload_to='matric_certificates/')),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smme_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cipc_reg', models.IntegerField()),
                ('operating_years', models.IntegerField()),
                ('sars_compliance', models.CharField(max_length=100)),
                ('cipc_docs', models.FileField(blank=True, null=True, upload_to='CIPC_docs/')),
                ('company_profile', models.FileField(blank=True, null=True, upload_to='Company_profile/')),
                ('bbbee_cert', models.FileField(blank=True, null=True, upload_to='BBBEE_certificates/')),
            ],
        ),
    ]