# Generated by Django 6.1 on 2026-09-25 20:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdp_code', models.CharField(help_text='Unique code provided to the SDP by a QCTO official.', max_length=50, unique=True)),
                ('accreditation_number', models.CharField(blank=True, help_text='Used in place of an SDP code only when no code has been issued.', max_length=50)),
                ('accreditation_start_date', models.DateField()),
                ('accreditation_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('nqf_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='National ID must contain exactly 13 digits.', regex='^\\d{13}$')])),
                ('learner_alternate_id', models.CharField(blank=True, max_length=100)),
                ('alternative_id_type', models.CharField(blank=True, choices=[('527', 'Passport / Foreign ID'), ('533', 'None'), ('565', 'Refugee'), ('538', 'Work Permit'), ('540', 'Birth Certificate'), ('570', 'Alternate ID → National ID')], max_length=3)),
                ('equity_code', models.CharField(choices=[('BA', 'Black African'), ('BC', 'Coloured'), ('BI', 'Indian/Asian'), ('Oth', 'Other'), ('U', 'Unknown'), ('Wh', 'White')], max_length=3)),
                ('nationality_code', models.CharField(choices=[('U', 'Unspecified'), ('SA', 'South Africa'), ('SDC', 'SADC except SA'), ('NAM', 'Namibia'), ('BOT', 'Botswana'), ('ZIM', 'Zimbabwe'), ('ANG', 'Angola'), ('MOZ', 'Mozambique'), ('LES', 'Lesotho'), ('SWA', 'Swaziland'), ('MAL', 'Malawi'), ('ZAM', 'Zambia'), ('MAU', 'Mauritius'), ('TAN', 'Tanzania'), ('SEY', 'Seychelles'), ('ZAI', 'Zaire'), ('ROA', 'Rest of Africa'), ('EUR', 'European countries'), ('AIS', 'Asian countries'), ('NOR', 'North American countries'), ('SOU', 'Central and South American countries'), ('AUS', 'Australia Oceania countries'), ('OOC', 'Other and rest of Oceania'), ('NOT', 'N/A: Institution')], max_length=10)),
                ('home_language_code', models.CharField(choices=[('Eng', 'English'), ('Afr', 'Afrikaans'), ('Oth', 'Other'), ('SASL', 'South African Sign Language'), ('Sep', 'sePedi'), ('Ses', 'seSotho'), ('Set', 'seTswana'), ('Swa', 'siSwati'), ('Tsh', 'tshiVenda'), ('Xho', 'isiXhosa'), ('Xit', 'xiTsonga'), ('Zul', 'isiZulu'), ('Nde', 'isiNdebele')], max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('citizen_resident_status', models.CharField(choices=[('SA', 'South Africa'), ('O', 'Other'), ('D', 'Dual (SA plus other)'), ('PR', 'Permanent Resident'), ('U', 'Unknown')], max_length=3)),
                ('socioeconomic_status_code', models.CharField(choices=[('01', 'Employed'), ('02', 'Unemployed, looking for work'), ('03', 'Not working – not looking for work'), ('04', 'Home-maker (not working)'), ('06', 'Scholar/student (not working)'), ('07', 'Pensioner/retired (not working)'), ('08', 'Not working – disabled person'), ('09', 'Not working – not wishing to work'), ('10', 'Not working – Not elsewhere classified'), ('97', 'N/A: Aged <15'), ('98', 'N/A: Institution'), ('U', 'Unspecified')], max_length=2)),
                ('disability_status_code', models.CharField(choices=[('N', 'None'), ('01', 'Sight (even with glasses)'), ('02', 'Hearing (even with a hearing aid)'), ('03', 'Communication (talking, listening)'), ('04', 'Physical (moving, standing, grasping)'), ('05', 'Intellectual (difficulties in learning); retardation'), ('06', 'Emotional (behavioural or psychological)'), ('07', 'Multiple'), ('09', 'Disabled but Unspecified')], max_length=2)),
                ('disability_rating', models.CharField(blank=True, choices=[('01', 'No difficulty'), ('02', 'Some difficulty'), ('03', 'A lot of difficulty'), ('04', 'Cannot do at all'), ('06', 'Cannot yet be determined'), ('60', 'May be part of multiple difficulties (TBC)'), ('70', 'May have difficulty (TBC)'), ('80', 'Former difficulty - none now')], max_length=2)),
                ('immigrant_status', models.CharField(choices=[('01', 'Immigrant'), ('02', 'Refugee'), ('03', 'SA Citizen')], max_length=2)),
                ('last_name', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('Prof', 'Prof')], max_length=20)),
                ('birth_date', models.DateField()),
                ('home_address_1', models.CharField(max_length=255)),
                ('home_address_2', models.CharField(max_length=255)),
                ('home_address_3', models.CharField(blank=True, max_length=255)),
                ('postal_address_1', models.CharField(max_length=255)),
                ('postal_address_2', models.CharField(max_length=255)),
                ('postal_address_3', models.CharField(blank=True, max_length=255)),
                ('home_postal_code', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Postal code must contain exactly 4 digits.', regex='^\\d{4}$')])),
                ('postal_postal_code', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Postal code must contain exactly 4 digits.', regex='^\\d{4}$')])),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('cell', models.CharField(blank=True, max_length=30)),
                ('fax', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('province_code', models.CharField(choices=[('1', 'Western Cape'), ('2', 'Eastern Cape'), ('3', 'Northern Cape'), ('4', 'Free State'), ('5', 'Kwazulu Natal'), ('6', 'North West'), ('7', 'Gauteng'), ('8', 'Mpumalanga'), ('9', 'Limpopo'), ('N', 'SA National (province unspecified)'), ('X', 'Outside SA')], max_length=1)),
                ('statssa_area_code', models.CharField(max_length=20)),
                ('popi_act_agree', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('popi_act_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='learner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_training_completion_date', models.DateField()),
                ('statement_of_results_status', models.CharField(choices=[('01', 'Statement of Results issued'), ('02', 'Statement of Results not yet issued')], max_length=2)),
                ('statement_of_results_date', models.DateField(blank=True, null=True)),
                ('assessment_centre_code', models.CharField(blank=True, max_length=50)),
                ('learner_readiness_for_eisa_type', models.CharField(choices=[('1', 'Enrolled'), ('2', 'RPL for Access to EISA determined by SDP'), ('3', 'Mixed Mode to EISA'), ('4', 'SDP Training and assessment for readiness to EISA'), ('5', 'SDP e-learning training and assessment for readiness to EISA'), ('6', 'RPL for Access to EISA determined by Assessment Partner/Quality Partner')], max_length=1)),
                ('flc_status', models.CharField(choices=[('01', 'FLC certificate (competent)'), ('02', 'RPL'), ('03', 'Grade 12/NCV Level 4 Maths/English pass'), ('04', 'Not yet competent'), ('05', 'FLC not completed yet'), ('06', 'Not applicable (qualification on NQF 5 and above)'), ('07', 'Enrolled for FLC'), ('08', 'N3 Mathematics and Business Language')], max_length=2)),
                ('flc_certificate_number', models.CharField(max_length=100)),
                ('date_stamp', models.DateField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accreditation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='learners.accreditation')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='learners.learnerprofile')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='learners.qualification')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('learner', 'qualification'), name='unique_learner_qualification_enrolment')],
            },
        ),
        migrations.CreateModel(
            name='QualificationAccreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accreditation_start_date', models.DateField()),
                ('accreditation_end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualification_accreditations', to='learners.accreditation')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accreditations', to='learners.qualification')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('provider', 'qualification'), name='unique_provider_qualification_accreditation')],
            },
        ),
    ]