# Generated by Django 6.1 on 2026-09-08 08:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='National ID must contain exactly 13 digits.', regex='^\\d{13}$')])),
                ('learner_alternate_id', models.CharField(blank=True, max_length=100)),
                ('alternative_id_type', models.CharField(blank=True, choices=[('527', 'Passport / Foreign ID'), ('533', 'None'), ('565', 'Refugee'), ('538', 'Work Permit'), ('540', 'Birth Certificate'), ('570', 'Alternate ID → National ID')], max_length=3)),
                ('equity_code', models.CharField(blank=True, max_length=3)),
                ('nationality_code', models.CharField(blank=True, max_length=10)),
                ('home_language_code', models.CharField(blank=True, max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('citizen_resident_status', models.CharField(blank=True, max_length=3)),
                ('socioeconomic_status_code', models.CharField(blank=True, max_length=3)),
                ('disability_status_code', models.CharField(blank=True, max_length=3)),
                ('disability_rating', models.CharField(blank=True, max_length=2)),
                ('immigrant_status', models.CharField(blank=True, max_length=2)),
                ('last_name', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('title', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField()),
                ('home_address_1', models.CharField(max_length=255)),
                ('home_address_2', models.CharField(blank=True, max_length=255)),
                ('home_address_3', models.CharField(blank=True, max_length=255)),
                ('postal_address_1', models.CharField(max_length=255)),
                ('postal_address_2', models.CharField(blank=True, max_length=255)),
                ('postal_address_3', models.CharField(blank=True, max_length=255)),
                ('home_postal_code', models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator(message='Postal code must contain exactly 4 digits.', regex='^\\d{4}$')])),
                ('postal_postal_code', models.CharField(blank=True, max_length=4, validators=[django.core.validators.RegexValidator(message='Postal code must contain exactly 4 digits.', regex='^\\d{4}$')])),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('cell', models.CharField(blank=True, max_length=30)),
                ('fax', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('province_code', models.CharField(blank=True, max_length=1)),
                ('statssa_area_code', models.CharField(blank=True, max_length=20)),
                ('popi_act_agree', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('popi_act_date', models.DateField(blank=True, null=True)),
                ('expected_training_completion_date', models.DateField(blank=True, null=True)),
                ('statement_of_results_status', models.CharField(blank=True, max_length=2)),
                ('statement_of_results_date', models.DateField(blank=True, null=True)),
                ('assessment_centre_code', models.CharField(blank=True, max_length=50)),
                ('learner_readiness_for_eisa_type', models.CharField(blank=True, max_length=1)),
                ('flc_status', models.CharField(blank=True, max_length=20)),
                ('flc_certificate_number', models.CharField(blank=True, max_length=100)),
                ('date_stamp', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='learner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
